// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: protobuf2
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Server.Protocols
{

    /// <summary>Holder for reflection information generated from protobuf2</summary>
    public static partial class Protobuf2Reflection
    {

        #region Descriptor
        /// <summary>File descriptor for protobuf2</summary>
        public static pbr::FileDescriptor Descriptor
        {
            get { return descriptor; }
        }
        private static pbr::FileDescriptor descriptor;

        static Protobuf2Reflection()
        {
            byte[] descriptorData = global::System.Convert.FromBase64String(
                string.Concat(
                  "Cglwcm90b2J1ZjISEHNlcnZlci5wcm90b2NvbHMiUgoKUHZQTWVzc2FnZRIM",
                  "CgR0eXBlGAEgASgPEg0KBWZsYWdzGAIgASgHEgsKA3NlcRgDIAEoBxIMCgRz",
                  "c2VxGAQgASgHEgwKBGJvZHkYBSABKAwiTwoRTmV0d29ya2luZ01lc3NhZ2US",
                  "DAoEdHlwZRgBIAEoDRIRCgd1bmtub3duGAMgASgMSAASEQoHY29udHJvbBgE",
                  "IAEoCUgAQgYKBGJvZHliBnByb3RvMw=="));
            descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
                new pbr::FileDescriptor[] { },
                new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Server.Protocols.PvPMessage), global::Server.Protocols.PvPMessage.Parser, new[]{ "Type", "Flags", "Seq", "Sseq", "Body" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Server.Protocols.NetworkingMessage), global::Server.Protocols.NetworkingMessage.Parser, new[]{ "Type", "Unknown", "Control" }, new[]{ "Body" }, null, null, null)
                }));
        }
        #endregion

    }
    #region Messages
    public sealed partial class PvPMessage : pb::IMessage<PvPMessage>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
#endif
    {
        private static readonly pb::MessageParser<PvPMessage> _parser = new pb::MessageParser<PvPMessage>(() => new PvPMessage());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pb::MessageParser<PvPMessage> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pbr::MessageDescriptor Descriptor
        {
            get { return global::Server.Protocols.Protobuf2Reflection.Descriptor.MessageTypes[0]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        pbr::MessageDescriptor pb::IMessage.Descriptor
        {
            get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public PvPMessage()
        {
            OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public PvPMessage(PvPMessage other) : this()
        {
            type_ = other.type_;
            flags_ = other.flags_;
            seq_ = other.seq_;
            sseq_ = other.sseq_;
            body_ = other.body_;
            _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public PvPMessage Clone()
        {
            return new PvPMessage(this);
        }

        /// <summary>Field number for the "type" field.</summary>
        public const int TypeFieldNumber = 1;
        private int type_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int Type
        {
            get { return type_; }
            set
            {
                type_ = value;
            }
        }

        /// <summary>Field number for the "flags" field.</summary>
        public const int FlagsFieldNumber = 2;
        private uint flags_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public uint Flags
        {
            get { return flags_; }
            set
            {
                flags_ = value;
            }
        }

        /// <summary>Field number for the "seq" field.</summary>
        public const int SeqFieldNumber = 3;
        private uint seq_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public uint Seq
        {
            get { return seq_; }
            set
            {
                seq_ = value;
            }
        }

        /// <summary>Field number for the "sseq" field.</summary>
        public const int SseqFieldNumber = 4;
        private uint sseq_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public uint Sseq
        {
            get { return sseq_; }
            set
            {
                sseq_ = value;
            }
        }

        /// <summary>Field number for the "body" field.</summary>
        public const int BodyFieldNumber = 5;
        private pb::ByteString body_ = pb::ByteString.Empty;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public pb::ByteString Body
        {
            get { return body_; }
            set
            {
                body_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
            }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override bool Equals(object other)
        {
            return Equals(other as PvPMessage);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool Equals(PvPMessage other)
        {
            if (ReferenceEquals(other, null))
            {
                return false;
            }
            if (ReferenceEquals(other, this))
            {
                return true;
            }
            if (Type != other.Type) return false;
            if (Flags != other.Flags) return false;
            if (Seq != other.Seq) return false;
            if (Sseq != other.Sseq) return false;
            if (Body != other.Body) return false;
            return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override int GetHashCode()
        {
            int hash = 1;
            if (Type != 0) hash ^= Type.GetHashCode();
            if (Flags != 0) hash ^= Flags.GetHashCode();
            if (Seq != 0) hash ^= Seq.GetHashCode();
            if (Sseq != 0) hash ^= Sseq.GetHashCode();
            if (Body.Length != 0) hash ^= Body.GetHashCode();
            if (_unknownFields != null)
            {
                hash ^= _unknownFields.GetHashCode();
            }
            return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override string ToString()
        {
            return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void WriteTo(pb::CodedOutputStream output)
        {
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
            output.WriteRawMessage(this);
#else
      if (Type != 0) {
        output.WriteRawTag(13);
        output.WriteSFixed32(Type);
      }
      if (Flags != 0) {
        output.WriteRawTag(21);
        output.WriteFixed32(Flags);
      }
      if (Seq != 0) {
        output.WriteRawTag(29);
        output.WriteFixed32(Seq);
      }
      if (Sseq != 0) {
        output.WriteRawTag(37);
        output.WriteFixed32(Sseq);
      }
      if (Body.Length != 0) {
        output.WriteRawTag(42);
        output.WriteBytes(Body);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
#endif
        }

#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output)
        {
            if (Type != 0)
            {
                output.WriteRawTag(13);
                output.WriteSFixed32(Type);
            }
            if (Flags != 0)
            {
                output.WriteRawTag(21);
                output.WriteFixed32(Flags);
            }
            if (Seq != 0)
            {
                output.WriteRawTag(29);
                output.WriteFixed32(Seq);
            }
            if (Sseq != 0)
            {
                output.WriteRawTag(37);
                output.WriteFixed32(Sseq);
            }
            if (Body.Length != 0)
            {
                output.WriteRawTag(42);
                output.WriteBytes(Body);
            }
            if (_unknownFields != null)
            {
                _unknownFields.WriteTo(ref output);
            }
        }
#endif

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int CalculateSize()
        {
            int size = 0;
            if (Type != 0)
            {
                size += 1 + 4;
            }
            if (Flags != 0)
            {
                size += 1 + 4;
            }
            if (Seq != 0)
            {
                size += 1 + 4;
            }
            if (Sseq != 0)
            {
                size += 1 + 4;
            }
            if (Body.Length != 0)
            {
                size += 1 + pb::CodedOutputStream.ComputeBytesSize(Body);
            }
            if (_unknownFields != null)
            {
                size += _unknownFields.CalculateSize();
            }
            return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(PvPMessage other)
        {
            if (other == null)
            {
                return;
            }
            if (other.Type != 0)
            {
                Type = other.Type;
            }
            if (other.Flags != 0)
            {
                Flags = other.Flags;
            }
            if (other.Seq != 0)
            {
                Seq = other.Seq;
            }
            if (other.Sseq != 0)
            {
                Sseq = other.Sseq;
            }
            if (other.Body.Length != 0)
            {
                Body = other.Body;
            }
            _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(pb::CodedInputStream input)
        {
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
            input.ReadRawMessage(this);
#else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 13: {
            Type = input.ReadSFixed32();
            break;
          }
          case 21: {
            Flags = input.ReadFixed32();
            break;
          }
          case 29: {
            Seq = input.ReadFixed32();
            break;
          }
          case 37: {
            Sseq = input.ReadFixed32();
            break;
          }
          case 42: {
            Body = input.ReadBytes();
            break;
          }
        }
      }
#endif
        }

#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input)
        {
            uint tag;
            while ((tag = input.ReadTag()) != 0)
            {
                switch (tag)
                {
                    default:
                        _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                        break;
                    case 13:
                        {
                            Type = input.ReadSFixed32();
                            break;
                        }
                    case 21:
                        {
                            Flags = input.ReadFixed32();
                            break;
                        }
                    case 29:
                        {
                            Seq = input.ReadFixed32();
                            break;
                        }
                    case 37:
                        {
                            Sseq = input.ReadFixed32();
                            break;
                        }
                    case 42:
                        {
                            Body = input.ReadBytes();
                            break;
                        }
                }
            }
        }
#endif

    }

    public sealed partial class NetworkingMessage : pb::IMessage<NetworkingMessage>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
#endif
    {
        private static readonly pb::MessageParser<NetworkingMessage> _parser = new pb::MessageParser<NetworkingMessage>(() => new NetworkingMessage());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pb::MessageParser<NetworkingMessage> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pbr::MessageDescriptor Descriptor
        {
            get { return global::Server.Protocols.Protobuf2Reflection.Descriptor.MessageTypes[1]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        pbr::MessageDescriptor pb::IMessage.Descriptor
        {
            get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public NetworkingMessage()
        {
            OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public NetworkingMessage(NetworkingMessage other) : this()
        {
            type_ = other.type_;
            switch (other.BodyCase)
            {
                case BodyOneofCase.Unknown:
                    Unknown = other.Unknown;
                    break;
                case BodyOneofCase.Control:
                    Control = other.Control;
                    break;
            }

            _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public NetworkingMessage Clone()
        {
            return new NetworkingMessage(this);
        }

        /// <summary>Field number for the "type" field.</summary>
        public const int TypeFieldNumber = 1;
        private uint type_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public uint Type
        {
            get { return type_; }
            set
            {
                type_ = value;
            }
        }

        /// <summary>Field number for the "unknown" field.</summary>
        public const int UnknownFieldNumber = 3;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public pb::ByteString Unknown
        {
            get { return bodyCase_ == BodyOneofCase.Unknown ? (pb::ByteString)body_ : pb::ByteString.Empty; }
            set
            {
                body_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
                bodyCase_ = BodyOneofCase.Unknown;
            }
        }

        /// <summary>Field number for the "control" field.</summary>
        public const int ControlFieldNumber = 4;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public string Control
        {
            get { return bodyCase_ == BodyOneofCase.Control ? (string)body_ : ""; }
            set
            {
                body_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
                bodyCase_ = BodyOneofCase.Control;
            }
        }

        private object body_;
        /// <summary>Enum of possible cases for the "body" oneof.</summary>
        public enum BodyOneofCase
        {
            None = 0,
            Unknown = 3,
            Control = 4,
        }
        private BodyOneofCase bodyCase_ = BodyOneofCase.None;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public BodyOneofCase BodyCase
        {
            get { return bodyCase_; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void ClearBody()
        {
            bodyCase_ = BodyOneofCase.None;
            body_ = null;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override bool Equals(object other)
        {
            return Equals(other as NetworkingMessage);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool Equals(NetworkingMessage other)
        {
            if (ReferenceEquals(other, null))
            {
                return false;
            }
            if (ReferenceEquals(other, this))
            {
                return true;
            }
            if (Type != other.Type) return false;
            if (Unknown != other.Unknown) return false;
            if (Control != other.Control) return false;
            if (BodyCase != other.BodyCase) return false;
            return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override int GetHashCode()
        {
            int hash = 1;
            if (Type != 0) hash ^= Type.GetHashCode();
            if (bodyCase_ == BodyOneofCase.Unknown) hash ^= Unknown.GetHashCode();
            if (bodyCase_ == BodyOneofCase.Control) hash ^= Control.GetHashCode();
            hash ^= (int)bodyCase_;
            if (_unknownFields != null)
            {
                hash ^= _unknownFields.GetHashCode();
            }
            return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override string ToString()
        {
            return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void WriteTo(pb::CodedOutputStream output)
        {
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
            output.WriteRawMessage(this);
#else
      if (Type != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(Type);
      }
      if (bodyCase_ == BodyOneofCase.Unknown) {
        output.WriteRawTag(26);
        output.WriteBytes(Unknown);
      }
      if (bodyCase_ == BodyOneofCase.Control) {
        output.WriteRawTag(34);
        output.WriteString(Control);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
#endif
        }

#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output)
        {
            if (Type != 0)
            {
                output.WriteRawTag(8);
                output.WriteUInt32(Type);
            }
            if (bodyCase_ == BodyOneofCase.Unknown)
            {
                output.WriteRawTag(26);
                output.WriteBytes(Unknown);
            }
            if (bodyCase_ == BodyOneofCase.Control)
            {
                output.WriteRawTag(34);
                output.WriteString(Control);
            }
            if (_unknownFields != null)
            {
                _unknownFields.WriteTo(ref output);
            }
        }
#endif

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int CalculateSize()
        {
            int size = 0;
            if (Type != 0)
            {
                size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Type);
            }
            if (bodyCase_ == BodyOneofCase.Unknown)
            {
                size += 1 + pb::CodedOutputStream.ComputeBytesSize(Unknown);
            }
            if (bodyCase_ == BodyOneofCase.Control)
            {
                size += 1 + pb::CodedOutputStream.ComputeStringSize(Control);
            }
            if (_unknownFields != null)
            {
                size += _unknownFields.CalculateSize();
            }
            return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(NetworkingMessage other)
        {
            if (other == null)
            {
                return;
            }
            if (other.Type != 0)
            {
                Type = other.Type;
            }
            switch (other.BodyCase)
            {
                case BodyOneofCase.Unknown:
                    Unknown = other.Unknown;
                    break;
                case BodyOneofCase.Control:
                    Control = other.Control;
                    break;
            }

            _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(pb::CodedInputStream input)
        {
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
            input.ReadRawMessage(this);
#else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Type = input.ReadUInt32();
            break;
          }
          case 26: {
            Unknown = input.ReadBytes();
            break;
          }
          case 34: {
            Control = input.ReadString();
            break;
          }
        }
      }
#endif
        }

#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input)
        {
            uint tag;
            while ((tag = input.ReadTag()) != 0)
            {
                switch (tag)
                {
                    default:
                        _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                        break;
                    case 8:
                        {
                            Type = input.ReadUInt32();
                            break;
                        }
                    case 26:
                        {
                            Unknown = input.ReadBytes();
                            break;
                        }
                    case 34:
                        {
                            Control = input.ReadString();
                            break;
                        }
                }
            }
        }
#endif

    }

    #endregion

}

#endregion Designer generated code
